# Generated by Django 4.2.24 on 2025-09-27 20:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='pdf_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('fee', 'Fee'), ('interest', 'Interest')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('pdf_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pdf_analyzer.pdfupload')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spending_patterns', models.JSONField(default=dict)),
                ('budgeting_recommendations', models.TextField()),
                ('financial_insights', models.TextField()),
                ('risk_assessment', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('gemini_model_used', models.CharField(default='gemini-pro', max_length=100)),
                ('pdf_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='pdf_analyzer.pdfupload')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_count', models.IntegerField()),
                ('percentage_of_expenses', models.DecimalField(decimal_places=2, max_digits=5)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_summaries', to='pdf_analyzer.aianalysis')),
            ],
            options={
                'unique_together': {('analysis', 'category_name')},
            },
        ),
    ]
